#!/usr/bin/env bash
#
#
set -e
cd "$(dirname "$0")/.."
OUT=include/gnm_shaders.h

objcopy_bin() {  # in.o out.bin
    llvm-objcopy-14 -O binary --only-section=.text "$1" "$2" 2>/dev/null \
        || llvm-objcopy -O binary --only-section=.text "$1" "$2"
}

emit() {  # symbol_name  source.s
    local name="$1" src="$2"
    clang -target amdgcn-amd-amdhsa -mcpu=gfx700 -nogpulib -c "$src" -o "/tmp/$name.o"
    objcopy_bin "/tmp/$name.o" "/tmp/$name.bin"
    local n; n=$(wc -c < "/tmp/$name.bin")
    echo "// $src -> $n bytes"
    echo "static const unsigned char $name[] = {"
    od -An -tx1 -v "/tmp/$name.bin" | awk '{for(i=1;i<=NF;i++)printf "0x%s,",$i; if(NF)print ""}'
    echo "};"
    echo "assembled $src -> $name ($n bytes)" >&2
}

{
    echo "// Auto-generated by shaders/build_shaders.sh. Do not edit by hand."
    echo "#pragma once"
    emit g_matvec_t_shader shaders/matvec_t.s
} > "$OUT"
echo "wrote $OUT" >&2
